# Generated by Django 4.0.4 on 2022-05-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
