# Generated by Django 4.0.4 on 2022-05-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('p_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('packagess_name', models.CharField(db_index=True, max_length=120)),
                ('destination_List', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1200)),
                ('price', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='packages_img')),
                ('cover_pick', models.IntegerField()),
                ('event', models.IntegerField()),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
