# Generated by Django 4.0.4 on 2022-05-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='event',
            field=models.CharField(max_length=120),
        ),
    ]
