# Generated by Django 4.0.4 on 2022-06-26 18:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event', models.CharField(choices=[('other', 'Other'), ('rafting', 'Rafting'), ('camping', 'Camping'), ('trekking', 'Trekking'), ('canoeing', 'Canoeing'), ('ziplining', 'Ziplining'), ('sky diving', 'Sky Diving'), ('paragliding', 'Paragliding'), ('rock climbing', 'Rock Climbing'), ('mountaineering', 'Mountaineering'), ('bungee jumping', 'Bungee Jumping'), ('mountain biking', 'Mountain Biking')], max_length=200, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('snacks', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(default='../../static/images/default_package.png', null=True, upload_to='')),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('coordinate', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('events', models.ManyToManyField(blank=True, to='dashboard.event')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.food')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120, null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, default='../../static/assets/images/default_package.png', null=True, upload_to='')),
                ('cover_image', models.ImageField(blank=True, default='../../static/assets/images/default_package.png', null=True, upload_to='')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('is_featured', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('booked', 'Booked'), ('ongoing', 'Ongoing')], default='unavailable', max_length=120)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.itinerary')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.place'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=120, null=True)),
                ('action', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('logged-in', 'Logged In'), ('logged-out', 'Logged Out'), ('banned', 'Banned'), ('unbanned', 'Unbanned')], max_length=120)),
                ('thing', models.CharField(blank=True, choices=[('food', 'Food'), ('event', 'Event'), ('place', 'Place'), ('package', 'Package'), ('itinerary', 'Itinerary')], max_length=120, null=True)),
                ('more', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
