# Generated by Django 4.0.4 on 2022-06-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='target',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('logged-in', 'Logged In'), ('logged-out', 'Logged Out'), ('banned', 'Banned'), ('unbanned', 'Unbanned')], max_length=120),
        ),
    ]
