# Generated by Django 4.0.1 on 2022-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activitylog_target_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.ManyToManyField(to='dashboard.Itinerary'),
        ),
        migrations.AlterField(
            model_name='place',
            name='events',
            field=models.ManyToManyField(blank=True, to='dashboard.Event'),
        ),
    ]
